keys:
  - &admin age1dundvc72hm2z2q2ka2rygx7kvetxz7z28xyg2anh83cz6g2v758sj6af9w
  - &home-server age1re56ac2p39gnw2gvvmk45d5sazf9lgrkvgc0ru0c8qvjl7hjm3dsvkzlgw
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *home-server